### ISSUE TITLE
Media rendering issue on Django 6.1

### ISSUE THREAD

**Issue by trey** [OmenApps/django-tomselect#64]
In my template, I have something like …

```html
{% load django_tomselect %}

...

<head>
{% tomselect_media_css %}
</head>
<body>

...

{% tomselect_media_js %}
</body>
```

This worked with Django 6.0.7, but upgrading to 6.1, I get the following errors:

```
AttributeError: 'Stylesheet' object has no attribute 'startswith'
Error rendering JS scripts: 'Script' object has no attribute 'startswith'
```

It gives the following as locations for the errors

```
... .venv/lib/python3.14/site-packages/django_tomselect/templatetags/django_tomselect.py", line 125, in render_css_links

... .venv/lib/python3.14/site-packages/django_tomselect/templatetags/django_tomselect.py", line 51, in to_static_url

... .venv/lib/python3.14/site-packages/django_tomselect/templatetags/django_tomselect.py", line 153, in render_js_scripts
```

Before the line `if path.startswith(("http://", "https://", "//"))`, if I print the `path`, I get something like…

```html
<script src="/static/django_tomselect/js/django-tomselect.js"></script>
```

…and not a string starting with `https://` as it expects.

Any idea what's happened between those versions of Django?

**Comment by nerdoc** [comment]
Root cause: Django 6.1 changed `forms.Media` to hold `Script` / `Stylesheet` objects (`django.forms.widgets.MediaAsset`) instead of plain path strings. `Media._normalize_js()` / `_normalize_css()` wrap every path, so `widget.media._css` and `widget.media._js` no longer yield strings.

`to_static_url()` calls `path.startswith(...)` on those objects, which raises `AttributeError`. `render_css_links()` and `render_js_scripts()` catch it, log it and return `""` — so `{% tomselect_media %}` silently renders **nothing**. The only visible symptom is the two log lines; the page just loses TomSelect.

(The printed `<script src="…"></script>` in the report is `MediaAsset.__str__`, which renders the full tag.)

Minimal repro, no third-party code:

```python
import django
from django.conf import settings
settings.configure(
    DEBUG=True, SECRET_KEY="x", STATIC_URL="/static/",
    DATABASES={"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}},
    INSTALLED_APPS=["django.contrib.contenttypes", "django.contrib.auth",
                    "django.contrib.staticfiles", "django_tomselect"],
    TEMPLATES=[{"BACKEND": "django.template.backends.django.DjangoTemplates",
                "APP_DIRS": True, "OPTIONS": {}}],
)
django.setup()

from django.template import Template, Context
print(repr(Template("{% load django_tomselect %}{% tomselect_media %}").render(Context({}))))
# Django 6.1.1 / django-tomselect 2026.6.2 -> ''
```

Suggested fix: drop `to_static_url()` from the media tags and let `Media` render itself. `Media.render_css()` and `Media.render_js()` have existed since long before the package's Django 4.2 floor, and they resolve `static()` themselves, so this works on every supported version:

```python
def render_css_links(media) -> str:
    return "\n".join(media.render_css())

def render_js_scripts(media) -> str:
    return "\n".join(media.render_js())
```

with the callers passing `widget.media` instead of `widget.media._css` / `._js`. Verified output on Django 6.1.1:

```html
<link href="/static/django_tomselect/vendor/tom-select/css/tom-select.default.css" media="all" rel="stylesheet">
<link href="/static/django_tomselect/css/django-tomselect.css" media="all" rel="stylesheet">
<script src="/static/django_tomselect/js/django-tomselect.js"></script>
```

Happy to send a PR if that direction is fine.

Credits: The fix was done using Claude Opus 5.
